Servidor en Express con Mongoose
undefined-academy/semana-8 pull request #5
Opened 2023-07-03 18:49 UTC by facu1391

Servidor en Express con la libreria express-generator

2023-07-04 00:58 UTC, jaimecabrera911 commented
Excelente trabajo implementaste muy bien los modelos y el servicio para poder crear y consultar productos

2023-07-04 01:04 UTC, jaimecabrera911 approved these changes
Excelente trabajo me parece que implementaste muy bien la creacion y consulta de productos

2023-07-04 02:36 UTC, facu1391 commented
Muchas gracias! Ya estaré modificando el .env  para dejar mockeado

2023-07-05 16:33 UTC, aitorias requested changes
Parece que tienes tu carpeta de usuario fuera del directorio `/express` y podría darte problemas cuando apliquen tu PR.

Y únicamente te faltaría preparar un documento `.env` de ejemplo con las variables de entorno a configurar por los usuarios para hacer la correcta conexión a la base de datos.

Por lo demás, las pruebas que realicé funcionan correctamente!! 👍  Así que genial!

2023-07-07 01:55 UTC, facu1391 commented
Muchas gracias por la corrección! Ya se hicieron los cambios mencionados

2023-07-11 06:07 UTC, aitorias approved these changes
Genial @facu1391! Ahora la estructura de directorios es correcta y el archivo .env de ejemplo ayudará a los compañeros a poder probar tu aplicación si lo desean 👍

2023-07-11 14:34 UTC, facu1391 commented
Muchas gracias por la corrección! Saludos

2023-07-12 00:41 UTC, merged